name: Upload to S3

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check secret keys
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}

      # AWS 자격 증명 설정
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 사용할 AWS 리전 설정 (예: us-east-1)

      # S3 버킷에 파일 업로드
      - name: Upload file to S3
        run: |
          aws s3 cp s3://minsbucket/test.py ./test.py
